### ISSUE TITLE
Array size limits on #jobs_create

### ISSUE THREAD

**Issue by zlahham** [NeverBounce/NeverBounceApi-Ruby#11]
Hi there,

I have been unable to successfully clean a list of over 200,000 emails through the /create endpoint using this client library as intended.

When using the #jobs_create method, it returns the following error:
```ruby
NeverBounce::API::AttributeError: Attribute must be set: server_obj
from /path/.bundle/ruby/2.4.0/gems/neverbounce-api-1.1.0/lib/never_bounce/api/feature/require_attr.rb:22:in `block in require_attr'
```

Here are the steps that I have followed:

```ruby
# Setup the client
client = NeverBounce::API::Client.new(api_key: "api_key_goes_here")

# The following array is only displayed for representational purposes.
# In reality the one that I'm sending has over 200K elements of [ID, Email]
users = [['ID goes here', 'Email goes here'], ['ID goes here', 'Email goes here'], ['ID goes here', 'Email goes here']]

resp2 = client.jobs_create(supplied_input: users, run_sample: true)

# Error is returned:
NeverBounce::API::AttributeError: Attribute must be set: server_obj
from /path/.bundle/ruby/2.4.0/gems/neverbounce-api-1.1.0/lib/never_bounce/api/feature/require_attr.rb:22:in `block in require_attr'
```
I have tested the method with a list of 150k entries, and it does work. It only starts to act funny after that number.

Can you please advise as to how we should break down the list for this to work effectively. It seems like it is not a good practice to do so, referring to your [usage guidelines](https://developers.neverbounce.com/v4.0/reference#usage-guidelines) in the documentation:

> - You should submit all the data you have for verification in a single job rather than multiple jobs. It is better to submit a single list of 10k emails rather than 10 lists of 1k emails each. This allows the verification system to properly deduplicate the emails and allows a more efficient verification.
> - If you're collecting data from external sources like a CRM or ERP, you should buffer the data locally and submit it as a single job rather than submitting each chunk of data separately.
> - Do NOT create more than 10 jobs for every 100k items per hour. Sending too many small jobs in a short amount of time can result in your account being locked and API access disabled. Exceptions can be made for some use cases, please contact us with your scenario if you'd like this exception to be made.

**Comment by mmollick** [comment]
Hey @zlahham, looks like you might be hitting the payload limitations for the size of the post request's body. When sending data directly in the request it's subject to our webservers `client_max_body_size` which is set to `25M`. Normally this will return a `413 Entity Too Large` error; not quite sure why that error isn't bubbling up in this case, we'll have to investigate that.

When customers need to upload 100k+ via the API we typically suggest they submit it using `remote_input` rather than `supplied_input`. This requires you to generate the CSV data locally and place the file in at a location that we can retrieve (e.g. a S3 bucket with a signed URL or on a webserver behind basic auth).

Alternatively if you can't use `remote_input` you could split the data into multiple chunks. In this case splitting the data into 50k or 100k chunks would be fine. Our usage guidelines are intended to discourage sending multiple small (< 1k) jobs frequently and encourage users to spool the emails into larger batches to send for verification.

**Comment by zlahham** [comment]
Thanks for your reply @mmollick. This makes more sense now.

Can I suggest that you kindly make this information more clear on the API Documentation as this has caused me a fair bit of confusion/frustration 😅 

In all cases, I reverted to one of the options that you suggested, so all good.

**Comment by mmollick** [comment]
Thanks for the suggestion, we'll definitely get that documented.
