### ISSUE TITLE
Timeout option is not working

### ISSUE THREAD

**Issue by terry90** [NeverBounce/NeverBounceApi-Ruby#7]
Some requests can take up to 25s (yeah, really)
I tried to put a timeout, 1s does nothing neither does 0.5s. I can't wait more than 2s for my requests and I can have up to 5 emails to check.

Can you add documentation for timeouts like the expected Exception to catch and the default (is there one?) ?

I don't see the timeout option passed to HTTParty btw

**Comment by mmollick** [comment]
Hi @terry90,

Most verification requests will complete well within the 2s window you're looking for. However, in some instances, verification requests can take several or even tens of seconds to complete. This is due to the real-time nature of the verification, we're at the mercy of the domain's email host. For larger email hosts like Gmail and Outlook/Hotmail this typically isn't an issue, but smaller hosts or shared hosting environments (e.g. Hostgator, 1&1, etc..) may take longer to respond. This is something that does come up from time to time and we are working on a solution for this. 

For now, we do suggest using the timeout parameter. This parameter is an internal timeout for the maximum amount of time we should spend trying to verify an email before returning an unknown. This isn't a hard client timeout and the actual round trip time for the request will be longer than the specified timeout.

I'll make sure to update the documentation to make the function of the timeout parameter more obvious.

**Comment by terry90** [comment]
Thank you for your fast response, yes I got it. When  I try a single check for small domains it can take a long time but it's alright.

I was just worried about the timeout not raising a Net::Timeout or something like this but I guess returning unknown is good enough. It should be documented as it can take a bit to understand.

Anyway, the gem is great!
